# module_name: ImageGram
author: Jabari Bell
# author_url: https://adyen.com
# github_url: https://github.com/adyen/Checkout-cocoa
clean: true

swift_version: 3.0

# copyright: '© 2015 [Adyen](http://adyen.com).'

custom_categories:
  - name: General
    children:
    - Checkout
    - PaymentData

  - name: UI
    children:
    - CheckoutViewController
    - CheckoutViewControllerDelegate
    - CheckoutHeaderView
    - CheckoutPaymentButton
    - CheckoutPaymentFieldView
    - CheckoutPaymentFieldDelegate

  - name: Card
    children:
    - CheckoutCardViewController
    - CardPaymentData
    - CardType
    - CardPaymentField
